name: Repo-Self-Updateg-Demo-02

on:
  workflow_dispatch:
    
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v4
      - name: Modify date and time
        run: |
          date > README2.md
          cat README2.md
      - name: Create grype configuration
        run: |
          cat <<EOF > test.txt
          ignore:
            # False positive, see https://github.com/anchore/grype/issues/558
            - vulnerability: CVE-2015-5237
              fix-state: unknown
              package:
                name: google.golang.org/protobuf
                version: v1.26.0
                type: go-module
                location: "/manager"
          EOF
      - name: Push to repository
        run: |
          git config --global user.name "MVR"
          git config --global user.email "mvr@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Auto Push on $now"
          git push
