name: Repo-Self-Updateg-Demo

on:
  workflow_dispatch:
    
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v3
      - name: Modify date and time
        run: |
          date > README2.md
          cat README2.md
      - name: Push to repository
        run: |
          git config --global user.name "MVR"
          git config --global user.email "mvr@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Auto Push on $now"
          git push
